title: Peng Rui's Homepage
page-top-title: Peng Rui
top-section-bg-text: Big shots are only little shots who keep shooting.
home-subtitle: Peng Rui &ensp;|&ensp;TezBaby
copyright-text: '&copy; Peng Rui 2023-2025. All Rights Reserved.'
